// <auto-generated/>
#nullable enable

using System;

namespace Microsoft.Extensions.Logging
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AutoLoggerMessageGenerator", "1.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.DebuggerStepThrough]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class GenericLoggerExtensions
    {
        public static void LogTrace(this ILogger @logger, string @message)
        {
            @logger.LogTrace(@message);
        }
        
        public static void LogTrace<T0>(this ILogger @logger, string @message, T0 @arg0)
        {
            @logger.LogTrace(@message, new object?[] { @arg0 });
        }
        
        public static void LogTrace<T0, T1>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogTrace(@message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogTrace<T0, T1, T2>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogTrace(@message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogTrace<T0, T1, T2, T3>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogTrace(@message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogTrace<T0, T1, T2, T3, T4>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogTrace(@message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogDebug(this ILogger @logger, string @message)
        {
            @logger.LogDebug(@message);
        }
        
        public static void LogDebug<T0>(this ILogger @logger, string @message, T0 @arg0)
        {
            @logger.LogDebug(@message, new object?[] { @arg0 });
        }
        
        public static void LogDebug<T0, T1>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogDebug(@message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogDebug<T0, T1, T2>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogDebug(@message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogDebug<T0, T1, T2, T3>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogDebug(@message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogDebug<T0, T1, T2, T3, T4>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogDebug(@message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogInformation(this ILogger @logger, string @message)
        {
            @logger.LogInformation(@message);
        }
        
        public static void LogInformation<T0>(this ILogger @logger, string @message, T0 @arg0)
        {
            @logger.LogInformation(@message, new object?[] { @arg0 });
        }
        
        public static void LogInformation<T0, T1>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogInformation(@message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogInformation<T0, T1, T2>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogInformation(@message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogInformation<T0, T1, T2, T3>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogInformation(@message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogInformation<T0, T1, T2, T3, T4>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogInformation(@message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogWarning(this ILogger @logger, string @message)
        {
            @logger.LogWarning(@message);
        }
        
        public static void LogWarning<T0>(this ILogger @logger, string @message, T0 @arg0)
        {
            @logger.LogWarning(@message, new object?[] { @arg0 });
        }
        
        public static void LogWarning<T0, T1>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogWarning(@message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogWarning<T0, T1, T2>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogWarning(@message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogWarning<T0, T1, T2, T3>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogWarning(@message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogWarning<T0, T1, T2, T3, T4>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogWarning(@message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogError(this ILogger @logger, string @message)
        {
            @logger.LogError(@message);
        }
        
        public static void LogError<T0>(this ILogger @logger, string @message, T0 @arg0)
        {
            @logger.LogError(@message, new object?[] { @arg0 });
        }
        
        public static void LogError<T0, T1>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogError(@message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogError<T0, T1, T2>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogError(@message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogError<T0, T1, T2, T3>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogError(@message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogError<T0, T1, T2, T3, T4>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogError(@message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogCritical(this ILogger @logger, string @message)
        {
            @logger.LogCritical(@message);
        }
        
        public static void LogCritical<T0>(this ILogger @logger, string @message, T0 @arg0)
        {
            @logger.LogCritical(@message, new object?[] { @arg0 });
        }
        
        public static void LogCritical<T0, T1>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogCritical(@message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogCritical<T0, T1, T2>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogCritical(@message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogCritical<T0, T1, T2, T3>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogCritical(@message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogCritical<T0, T1, T2, T3, T4>(this ILogger @logger, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogCritical(@message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        
        public static void LogTrace(this ILogger @logger, Exception? @exception, string @message)
        {
            @logger.LogTrace(@exception, @message);
        }
        
        public static void LogTrace<T0>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogTrace(@exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogTrace<T0, T1>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogTrace(@exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogTrace<T0, T1, T2>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogTrace(@exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogTrace<T0, T1, T2, T3>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogTrace(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogTrace<T0, T1, T2, T3, T4>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogTrace(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogDebug(this ILogger @logger, Exception? @exception, string @message)
        {
            @logger.LogDebug(@exception, @message);
        }
        
        public static void LogDebug<T0>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogDebug(@exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogDebug<T0, T1>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogDebug(@exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogDebug<T0, T1, T2>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogDebug(@exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogDebug<T0, T1, T2, T3>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogDebug(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogDebug<T0, T1, T2, T3, T4>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogDebug(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogInformation(this ILogger @logger, Exception? @exception, string @message)
        {
            @logger.LogInformation(@exception, @message);
        }
        
        public static void LogInformation<T0>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogInformation(@exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogInformation<T0, T1>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogInformation(@exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogInformation<T0, T1, T2>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogInformation(@exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogInformation<T0, T1, T2, T3>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogInformation(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogInformation<T0, T1, T2, T3, T4>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogInformation(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogWarning(this ILogger @logger, Exception? @exception, string @message)
        {
            @logger.LogWarning(@exception, @message);
        }
        
        public static void LogWarning<T0>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogWarning(@exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogWarning<T0, T1>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogWarning(@exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogWarning<T0, T1, T2>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogWarning(@exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogWarning<T0, T1, T2, T3>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogWarning(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogWarning<T0, T1, T2, T3, T4>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogWarning(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogError(this ILogger @logger, Exception? @exception, string @message)
        {
            @logger.LogError(@exception, @message);
        }
        
        public static void LogError<T0>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogError(@exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogError<T0, T1>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogError(@exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogError<T0, T1, T2>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogError(@exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogError<T0, T1, T2, T3>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogError(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogError<T0, T1, T2, T3, T4>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogError(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogCritical(this ILogger @logger, Exception? @exception, string @message)
        {
            @logger.LogCritical(@exception, @message);
        }
        
        public static void LogCritical<T0>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogCritical(@exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogCritical<T0, T1>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogCritical(@exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogCritical<T0, T1, T2>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogCritical(@exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogCritical<T0, T1, T2, T3>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogCritical(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogCritical<T0, T1, T2, T3, T4>(this ILogger @logger, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogCritical(@exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        
        public static void LogTrace(this ILogger @logger, EventId @eventId, string @message)
        {
            @logger.LogTrace(@eventId, @message);
        }
        
        public static void LogTrace<T0>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0)
        {
            @logger.LogTrace(@eventId, @message, new object?[] { @arg0 });
        }
        
        public static void LogTrace<T0, T1>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogTrace(@eventId, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogTrace<T0, T1, T2>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogTrace(@eventId, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogTrace<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogTrace(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogTrace<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogTrace(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogDebug(this ILogger @logger, EventId @eventId, string @message)
        {
            @logger.LogDebug(@eventId, @message);
        }
        
        public static void LogDebug<T0>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0)
        {
            @logger.LogDebug(@eventId, @message, new object?[] { @arg0 });
        }
        
        public static void LogDebug<T0, T1>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogDebug(@eventId, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogDebug<T0, T1, T2>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogDebug(@eventId, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogDebug<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogDebug(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogDebug<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogDebug(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogInformation(this ILogger @logger, EventId @eventId, string @message)
        {
            @logger.LogInformation(@eventId, @message);
        }
        
        public static void LogInformation<T0>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0)
        {
            @logger.LogInformation(@eventId, @message, new object?[] { @arg0 });
        }
        
        public static void LogInformation<T0, T1>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogInformation(@eventId, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogInformation<T0, T1, T2>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogInformation(@eventId, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogInformation<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogInformation(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogInformation<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogInformation(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogWarning(this ILogger @logger, EventId @eventId, string @message)
        {
            @logger.LogWarning(@eventId, @message);
        }
        
        public static void LogWarning<T0>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0)
        {
            @logger.LogWarning(@eventId, @message, new object?[] { @arg0 });
        }
        
        public static void LogWarning<T0, T1>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogWarning(@eventId, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogWarning<T0, T1, T2>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogWarning(@eventId, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogWarning<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogWarning(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogWarning<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogWarning(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogError(this ILogger @logger, EventId @eventId, string @message)
        {
            @logger.LogError(@eventId, @message);
        }
        
        public static void LogError<T0>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0)
        {
            @logger.LogError(@eventId, @message, new object?[] { @arg0 });
        }
        
        public static void LogError<T0, T1>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogError(@eventId, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogError<T0, T1, T2>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogError(@eventId, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogError<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogError(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogError<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogError(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogCritical(this ILogger @logger, EventId @eventId, string @message)
        {
            @logger.LogCritical(@eventId, @message);
        }
        
        public static void LogCritical<T0>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0)
        {
            @logger.LogCritical(@eventId, @message, new object?[] { @arg0 });
        }
        
        public static void LogCritical<T0, T1>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogCritical(@eventId, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogCritical<T0, T1, T2>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogCritical(@eventId, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogCritical<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogCritical(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogCritical<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogCritical(@eventId, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        
        public static void LogTrace(this ILogger @logger, EventId @eventId, Exception? @exception, string @message)
        {
            @logger.LogTrace(@eventId, @exception, @message);
        }
        
        public static void LogTrace<T0>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogTrace(@eventId, @exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogTrace<T0, T1>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogTrace(@eventId, @exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogTrace<T0, T1, T2>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogTrace(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogTrace<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogTrace(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogTrace<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogTrace(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogDebug(this ILogger @logger, EventId @eventId, Exception? @exception, string @message)
        {
            @logger.LogDebug(@eventId, @exception, @message);
        }
        
        public static void LogDebug<T0>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogDebug(@eventId, @exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogDebug<T0, T1>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogDebug(@eventId, @exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogDebug<T0, T1, T2>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogDebug(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogDebug<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogDebug(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogDebug<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogDebug(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogInformation(this ILogger @logger, EventId @eventId, Exception? @exception, string @message)
        {
            @logger.LogInformation(@eventId, @exception, @message);
        }
        
        public static void LogInformation<T0>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogInformation(@eventId, @exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogInformation<T0, T1>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogInformation(@eventId, @exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogInformation<T0, T1, T2>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogInformation(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogInformation<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogInformation(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogInformation<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogInformation(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogWarning(this ILogger @logger, EventId @eventId, Exception? @exception, string @message)
        {
            @logger.LogWarning(@eventId, @exception, @message);
        }
        
        public static void LogWarning<T0>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogWarning(@eventId, @exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogWarning<T0, T1>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogWarning(@eventId, @exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogWarning<T0, T1, T2>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogWarning(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogWarning<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogWarning(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogWarning<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogWarning(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogError(this ILogger @logger, EventId @eventId, Exception? @exception, string @message)
        {
            @logger.LogError(@eventId, @exception, @message);
        }
        
        public static void LogError<T0>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogError(@eventId, @exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogError<T0, T1>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogError(@eventId, @exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogError<T0, T1, T2>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogError(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogError<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogError(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogError<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogError(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        public static void LogCritical(this ILogger @logger, EventId @eventId, Exception? @exception, string @message)
        {
            @logger.LogCritical(@eventId, @exception, @message);
        }
        
        public static void LogCritical<T0>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0)
        {
            @logger.LogCritical(@eventId, @exception, @message, new object?[] { @arg0 });
        }
        
        public static void LogCritical<T0, T1>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1)
        {
            @logger.LogCritical(@eventId, @exception, @message, new object?[] { @arg0, @arg1 });
        }
        
        public static void LogCritical<T0, T1, T2>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2)
        {
            @logger.LogCritical(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2 });
        }
        
        public static void LogCritical<T0, T1, T2, T3>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3)
        {
            @logger.LogCritical(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3 });
        }
        
        public static void LogCritical<T0, T1, T2, T3, T4>(this ILogger @logger, EventId @eventId, Exception? @exception, string @message, T0 @arg0, T1 @arg1, T2 @arg2, T3 @arg3, T4 @arg4)
        {
            @logger.LogCritical(@eventId, @exception, @message, new object?[] { @arg0, @arg1, @arg2, @arg3, @arg4 });
        }
        
        
        
    }
}
