namespace AutoLoggerMessageGenerator;

internal static class Constants
{
    public const string DefaultLoggingNamespace = "Microsoft.Extensions.Logging";
    public const string GeneratorNamespace = $"{DefaultLoggingNamespace}.AutoLoggerMessage";

    public const string InterceptorNamespace = "System.Runtime.CompilerServices";
    public const string InterceptorAttributeName = "InterceptsLocationAttribute";

    public const string LogMethodPrefix = "Log_";
    public const string LoggerClassName = "AutoLoggerMessage";
    
    /// <summary>
    /// Support for an arbitrary number of logging parameters. LoggerMessage.Define supports a maximum of six.
    /// Must be synced with LoggerMessageGenerator.Emitter;
    /// </summary>
    public const int MaxLogParameters = 6;

    public const string ExcludeFromCoverageAttribute =
        "[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]";
    public const string DebuggerStepThroughAttribute =
        "[System.Diagnostics.DebuggerStepThrough]";
    public static readonly string GeneratedCodeAttribute =
        $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(" +
        $"\"{typeof(Generators.AutoLoggerMessageGenerator).Assembly.GetName().Name}\", " +
        $"\"{typeof(Generators.AutoLoggerMessageGenerator).Assembly.GetName().Version}\")]";
    public const string EditorNotBrowsableAttribute = "[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]";

    public static string GeneratedFileHeader => """
                                                // <auto-generated/>
                                                #nullable enable

                                                using System;

                                                """;
}
